#Slaat hierbij de variabelen van de juiste sequenties op
besanas = ("""MASEARGDKLWGGRFSGSTDPIMEKLNSSIAYDQRLSEVDIQGSMAYAKALEKAGILTKTELEKILSGLEKISEEWSKGVFVVKQSDEDIHTANERRLKELIGDIAGKLHTGRSRNDQVVTDLKLFMKNSLSIISTHLLQLIKTLVERAAIEIDVILPGYTHLQKAQPIRWSQFLLSHAVALTRDSERLGEVKKRINVLPLGSGALAGNPLDIDREMLRSELEFASISLNSMDAISERDFVVEFLSFATLLMIHLSKMAEDLIIYSTSEFGFLTLSDAFSTGSSLMPQKKNPDSLELIRSKAGRVFGRLASILMVLKGLPSTYNKDLQEDKEAVFDVVDTLTAVLQVATGVISTLQISKENMEKALTPEMLATDLALYLVRKGVPFRQAHTASGKAVHLAETKGITINKLSLEDLKSISPQFSSDVSQVFNFVNSVEQYTALAGTAKSSVTTQIEQLRELMKKQKEQA""")
besecoli = ("""MALWGGRFTQAADQRFKQFNDSLRFDYRLAEQDIVGSVAWSKALVTVGVLTAEEQAQLEEALNVLLEDVRARPQQILESDAEDIHSWVEGKLIDKVGQLGKKLHTGRSRNDQVATDLKLWCKDTVSELLTANRQLQSALVETAQNNQDAVMPGYTHLQRAQPVTFAHWCLAYVEMLARDESRLQDALKRLDVSPLGCGALAGTAYEIDREQLAGWLGFASATRNSLDSVSDRDHVLELLSAAAIGMVHLSRFAEDLIFFNTGEAGFVELSDRVTSGSSLMPQKKNPDALELIRGKCGRVQGALTGMMMTLKGLPLAYNKDMQEDKEGLFDALDTWLDCLHMAALVLDGIQVKRPRCQEAAQQGYANATELADYLVAKGVPFREAHHIVGEAVVEAIRQGKPLEDLPLSELQKFSQVIDEDVYPILSLQSCLDKRAAKGGVSPQQVAQAIAFAQARLG""")
besmacaca = ("""MASESGKLWGGRFVGAVDPIMEKFNASIAYDRHLWEVDVQGSKAYSRGLEKAGLLTKAEMDQILHGLDKVAEEWAQCTFKLSPNDEDIHTANERRLKELIGETAGKLHTGRSRNDQVVTDLRLWMRQTCSTLSGLLWELIRTMVDRAEAERDVLFPGYTHLQRAQPIRWSHWILSHAVALTRDSERLLEVRKRINVLPLGSGAIAGNPLSVDRELLRAELNFGAITLNSMDATSERDFVAEFLFWASLCMTHLSRMAEDLILYCTKEFSFVQLSDAYSTGSSLMPQKKNPDSLELIRSKAGRVFGRCAGLLMTLKGLPSTYNKDLQEDKEAVFEVSDTMSAVLQVATGVISTLQIHRENMGQALSPDMLATDLAYYLVRKGMPFRQAHEASGKAVFMAETKGVALNELSLQELQTISPLFSGDVSCVWDYGHSVEQYGALGGTARSSVDWQIRQVRALLQTQQA""")
besrattus = ("""MASESGKLWGGRFAGSVDPTMDKFNSSIAYDRHLWNVDLQGSKAYSRGLEKAGLLTKAEMQQILQGLDKVAEEWAQGIFKLYPNDEDIHTANERRLKELIGEAAGKLHTGRSRNDQVVTDLRLWMRQTYSKLSTFLKVLIEAMVDRAEAECEVLFPGYTHLQRAQPIRWSHWILSHAVALTRDLERLKEVQKRINVLPLGSGAIAGNPLGVDREFLCAELNFGAITLNSMDATSERDFVAEFLFWASLCMTHLSRMAEDLILYGTKEFNFVQLSDAYSTGSSLMPQKKNPDSLELIRSKARRVFGRCAGLLMTLKGLPSTYNKDLQEDKEAVFEVSDTMTAVLQVATGVISTLQIHRENMAQALSPDMLATDLAYYLVRKGMPFRQAHEASGKAVVVAEMKGVALNQLSLQELQTVSPLFSSDVNLVWDYSHSVEQYTALGGTAQSSVEWQISQVRALLQM""")
bespombe = ("""MAEKSSKKLWGGRFSGATDPLMAEFNKSIYSGKEMCEEDVIGSMAYAKALCQKNVISEEELNSILKGLEQIQREWNSGQFVLEPSDEDVHTANERRLTEIIGDVAGKLHTGRSRNDQVTTDLRLWLCRKIKEVEVYVINLLKVFTNRAEMEIDVIMSGYTHLQRAQPVRWSHFLMSHALPLLGDLGRLRQLYTRVSQLPLGAGALAGNPFNVDREFLRKELGFEGIIMNSMNAVGDRDFVIEFMFWAGMVMLHISRFAEDLIIYSSSEFGFVTLSDAYSTGSSIMPQKKNPDSLELLRGKSGRVLGDMIGLMITVKGTPTTYNKDLQEDKEPLFDAFKTVSDSLQILTGVVSTLTINPTKIAESLTPDLLATDLAEYLVRKGLPFRQTHHISGSAVRMAEERNTTLDKLSVSDLQSLHPLFDEDVSKVFNYEESVEKRCSIGGTAKHCVQEQIEHIRSAIL""")

#Vergelijkt of het aantal ACGT of N gelijk is aan het totale aantal tekens
nanas = besanas.count("")
a = besanas.count("A")
c = besanas.count("C")
g = besanas.count("G")
t = besanas.count("T")
n = besanas.count("N")
eindanas = a + c + g + t + n

if  nanas != eindanas:

#Telt het aantal D,E,R en K'tjes en print ze vervolgens.
    print("Anas is eiwit")
    da = besanas.count("D")
    ea = besanas.count("E")
    ra = besanas.count("R")
    ka = besanas.count("K")
    print (da ,""" D aminozuren in Anas""")
    print (ea ," E aminozuren in Anas")
    print (ra ," R aminozuren in Anas")
    print (ka ," K aminozuren in Anas")
else:
    print("Anas is geen eiwit")
    
print (nanas)



necoli = besecoli.count("")
a = besecoli.count("A")
c = besecoli.count("C")
g = besecoli.count("G")
t = besecoli.count("T")
n = besecoli.count("N")

eindecoli = a + c + g + t + n

if  necoli != eindecoli:
    print("E-coli is eiwit")
else:
    print("E-coli is dna")
    
print (necoli)





nmacaca = besmacaca.count("")
a = besmacaca.count("A")
c = besmacaca.count("C")
g = besmacaca.count("G")
t = besmacaca.count("T")
n = besmacaca.count("N")

eindmacaca = a + c + g + t + n

if  nmacaca != eindmacaca:
    print("Macaca is eiwit")
else:
    print("Macaca is dna")
    
print (nmacaca)




nrattus = besrattus.count("")
a = besrattus.count("A")
c = besrattus.count("C")
g = besrattus.count("G")
t = besrattus.count("T")
n = besrattus.count("N")

eindrattus = a + c + g + t + n

if  nrattus != eindrattus:
    print("Rattus is eiwit")
else:
    print("Rattus is dna")
    
print (nrattus)



npombe = bespombe.count("")
a = bespombe.count("A")
c = bespombe.count("C")
g = bespombe.count("G")
t = bespombe.count("T")
n = bespombe.count("N")

eindpombe = a + c + g + t + n

if  npombe != eindpombe:
    print("Pombe is eiwit")
else:
    print("Pombe is dna")
    
print (npombe)

